### ISSUE TITLE
Sampling time in test

### ISSUE THREAD

**Issue by lfb-1** [JunwenBai/MPVAE#1]
Hi,

I notice that in training and testing the sampling times are very different. May I ask why? Can I use 10000 for training?

Cheers

**Comment by JunwenBai** [comment]
The main concerns are the speed and memory. Of course, more samples bring more accurate estimation. You can use 10000 samples in training, but it would be slower and consumes more memory. Since testing is less frequent and does not require backprop, we use 10000 samples for better inference, and would not hurt the speed much.

**Comment by lfb-1** [comment]
Thanks. That is clear now.
